services:
  nestjs:
    image: node:18.18.2
    restart: always
    depends_on:
      - mysql
      - localstack
    links:
      - mysql
      - localstack
    ports:
      - 3000:3000
    volumes:
      - ../:/workspace
      # - /workspace/node_modules/
      # - /workspace/dist/
    environment:
      - PNPM_HOME=/home/node/.local/share/pnpm
      - TZ=Asia/Seoul
      - LC_ALL:en_US.UTF-8
    command: sleep infinity

  mysql:
    image: mysql:8.4.0
    restart: always
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE="fliption_auth"
      - MYSQL_USER="fliption"
      - MYSQL_PASSWORD="fliption"
      - TZ=Asia/Seoul
      - mysql-native-password=ON
    command:
      - --init_connect="SET collation_connection = utf8mb4_unicode_ci"
      - --init_connect="SET NAMES utf8mb4"
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=500

  localstack:
    container_name: localstack
    environment:
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localhost
      - TEST_AWS_ACCOUNT_ID=000000000000
      - AWS_DEFAULT_REGION=us-west-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - KINESIS_STREAM_SHARDS=1
      - KINESIS_ERROR_PROBABILITY=0.0
      - KINESIS_STREAM_NAME=kinesis-stream
      - KINESIS_PROVIDER=kinesalite
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
